import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { PromptOptions } from "@openuidev/react-lang";
import { chatOpenUILibrary } from "../src/lib/openui/chat-library";
import { OPENUI_FENCE_LANG } from "../src/lib/openui/openui-config";

/**
 * Build-time generator for the OpenUI system-prompt block.
 *
 * Imports the React-backed library here (safe in a plain Node/tsx process) and
 * writes the generated instruction string to a plain TS module that the API
 * route can import without pulling in the React renderer.
 *
 * Prompt options live here (not in the app) because this is their only
 * consumer: the running app uses the generated string, not these options.
 *
 * - `toolCalls`/`bindings` are disabled so the model never emits Query(),
 *   Mutation(), @Run, or $variables. All data access still goes through the
 *   normal chat + MCP tool path.
 * - `inlineMode` lets the model answer in plain text and optionally attach a
 *   single fenced OpenUI block, instead of being forced to always return UI.
 *
 * Run with: pnpm generate:openui-prompt
 */
const OPENUI_PROMPT_OPTIONS: PromptOptions = {
  toolCalls: false,
  bindings: false,
  inlineMode: true,
  preamble:
    "OPTIONAL STRUCTURED UI: In addition to your normal Markdown reply, you MAY render a compact visual block using OpenUI Lang. Use it only when it genuinely helps (summaries, detail rows, lists of choices, or confirming a completed action). For simple conversational replies, plain text is better.",
  additionalRules: [
    `When you include a structured UI block, output it as a fenced code block tagged \`${OPENUI_FENCE_LANG}\` (for example: \`\`\`${OPENUI_FENCE_LANG} ... \`\`\`). Everything outside the block is rendered as normal Markdown.`,
    "Always keep a brief plain-text sentence outside the code block so the reply is still readable if the UI block is not shown.",
    "The first statement inside the block MUST be `root = Card([...])`.",
    "NEVER use Query(...), Mutation(...), @Run, @Set, @Reset, or $variables. This UI is display-only; the user always responds in plain text.",
    "Do not put database UUIDs or the hidden (ref: ...) / (intent: ...) metadata inside the UI block.",
    "Emit at most one OpenUI block per reply.",
  ],
  examples: [
    [
      "root = Card([heading, details, note])",
      'heading = TextContent("Booking summary", "large-heavy")',
      "details = Stack([d1, d2, d3])",
      'd1 = KeyValue("Facility", "Study Room 202")',
      'd2 = KeyValue("Date", "2026-05-29")',
      'd3 = KeyValue("Time", "10:00-12:00")',
      'note = TextContent("Shall I go ahead and book this?", "default")',
    ].join("\n"),
    [
      "root = Card([prompt, choices])",
      'prompt = TextContent("Which section would you like?", "default")',
      'choices = OptionList(["Section A - Mon 9:00", "Section B - Wed 13:00"], true)',
    ].join("\n"),
  ],
};

const prompt = chatOpenUILibrary.prompt(OPENUI_PROMPT_OPTIONS);

const scriptDir = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(scriptDir, "../src/generated/openui-system-prompt.ts");

const banner = [
  "// AUTO-GENERATED by scripts/generate-openui-prompt.mts - do not edit by hand.",
  "// Regenerate with: pnpm generate:openui-prompt",
].join("\n");

const contents = `${banner}\nexport const OPENUI_SYSTEM_PROMPT = ${JSON.stringify(
  prompt,
)};\n`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, contents);

console.log(
  `Generated OpenUI system prompt (${prompt.length} chars) -> ${outPath}`,
);
